//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SprinklerNetCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SprinklerNetCore.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DarkSky API key.
        /// </summary>
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation.
        /// </summary>
        public static string AutomationTitle {
            get {
                return ResourceManager.GetString("AutomationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closer sprinkler after.
        /// </summary>
        public static string CloseAfter {
            get {
                return ResourceManager.GetString("CloseAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create typical program.
        /// </summary>
        public static string CreateTypical {
            get {
                return ResourceManager.GetString("CreateTypical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date and time.
        /// </summary>
        public static string DateTimeStart {
            get {
                return ResourceManager.GetString("DateTimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit typical.
        /// </summary>
        public static string EditTypical {
            get {
                return ResourceManager.GetString("EditTypical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must be a number.
        /// </summary>
        public static string ErrorMustBeNumber {
            get {
                return ResourceManager.GetString("ErrorMustBeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather forecast.
        /// </summary>
        public static string Forecast {
            get {
                return ResourceManager.GetString("Forecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparent Temp °C.
        /// </summary>
        public static string ForecastApparentTemp {
            get {
                return ResourceManager.GetString("ForecastApparentTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Temp °C.
        /// </summary>
        public static string ForecastHighTemp {
            get {
                return ResourceManager.GetString("ForecastHighTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string ForecastIcon {
            get {
                return ResourceManager.GetString("ForecastIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings for the forecast and automation.
        /// </summary>
        public static string ForecastIOSettings {
            get {
                return ResourceManager.GetString("ForecastIOSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Temp °C.
        /// </summary>
        public static string ForecastLowTemp {
            get {
                return ResourceManager.GetString("ForecastLowTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do we need to sprinkle?.
        /// </summary>
        public static string ForecastNeedSprinkler {
            get {
                return ResourceManager.GetString("ForecastNeedSprinkler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No forecast available.
        /// </summary>
        public static string ForecastNoneAvailable {
            get {
                return ResourceManager.GetString("ForecastNoneAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction percentage.
        /// </summary>
        public static string ForecastPercentageCorrection {
            get {
                return ResourceManager.GetString("ForecastPercentageCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prec Intens.
        /// </summary>
        public static string ForecastPrecIntens {
            get {
                return ResourceManager.GetString("ForecastPrecIntens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prec Prob %.
        /// </summary>
        public static string ForecastPrecProb {
            get {
                return ResourceManager.GetString("ForecastPrecProb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prec Type.
        /// </summary>
        public static string ForecastPrecType {
            get {
                return ResourceManager.GetString("ForecastPrecType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string ForecastSummary {
            get {
                return ResourceManager.GetString("ForecastSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp °C.
        /// </summary>
        public static string ForecastTemp {
            get {
                return ResourceManager.GetString("ForecastTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string ForecastTime {
            get {
                return ResourceManager.GetString("ForecastTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forecast information.
        /// </summary>
        public static string ForecastTitle {
            get {
                return ResourceManager.GetString("ForecastTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Speed km/h.
        /// </summary>
        public static string ForecastWindSpeed {
            get {
                return ResourceManager.GetString("ForecastWindSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full automation with forecast, actuals and automatic programming.
        /// </summary>
        public static string FullAutomationMode {
            get {
                return ResourceManager.GetString("FullAutomationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature and rain ranges for automation.
        /// </summary>
        public static string FuzzySprinklers {
            get {
                return ResourceManager.GetString("FuzzySprinklers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No history data.
        /// </summary>
        public static string HistoryNoData {
            get {
                return ResourceManager.GetString("HistoryNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string HistoryTitle {
            get {
                return ResourceManager.GetString("HistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is now {0}, if not, then change the time zone in the &lt;a href=&quot;/Settings&quot;&gt;settings&lt;/a&gt;..
        /// </summary>
        public static string HomeDateTime {
            get {
                return ResourceManager.GetString("HomeDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///        This sprinkler is running on &lt;a href=&quot;https://docs.microsoft.com/aspnet/core/&quot;&gt;ASP.NET Core&lt;/a&gt;, using native &lt;a href=&quot;https://github.com/dotnet/iot&quot;&gt;System.Device.Gpio&lt;/a&gt; and in an &lt;a href=&quot;https://azure.microsoft.com/services/iot-edge/
        ///&quot;&gt;Azure IoT Edge&lt;/a&gt; environement
        ///    &lt;/p&gt;
        ///    &lt;p&gt;Learn more about the solution on &lt;a href=&quot;https://github.com/ellerbach&quot;&gt;Laurent Ellerbach&apos;s GitHub&lt;/a&gt;&lt;/p&gt;
        ///    &lt;br /&gt;
        ///
        ///    &lt;h2&gt;You need to be an approved user and be connected to control the sprinklers.&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HomeInformation {
            get {
                return ResourceManager.GetString("HomeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This site uses cookies but don&apos;t store anything private in them. It&apos;s just to make navigation easier..
        /// </summary>
        public static string HomePrivacy {
            get {
                return ResourceManager.GetString("HomePrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string HomeWelcome {
            get {
                return ResourceManager.GetString("HomeWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to home.
        /// </summary>
        public static string IndexBackToHome {
            get {
                return ResourceManager.GetString("IndexBackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string IndexBackToList {
            get {
                return ResourceManager.GetString("IndexBackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string IsClosed {
            get {
                return ResourceManager.GetString("IsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it humid?.
        /// </summary>
        public static string IsHumid {
            get {
                return ResourceManager.GetString("IsHumid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is input inverted?.
        /// </summary>
        public static string IsInverted {
            get {
                return ResourceManager.GetString("IsInverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string IsOpen {
            get {
                return ResourceManager.GetString("IsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language for forecasts.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all programs.
        /// </summary>
        public static string ListAllPrograms {
            get {
                return ResourceManager.GetString("ListAllPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of sprinklers.
        /// </summary>
        public static string MaxSprinklers {
            get {
                return ResourceManager.GetString("MaxSprinklers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is sprinkling needed?.
        /// </summary>
        public static string NeedTo {
            get {
                return ResourceManager.GetString("NeedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is sprinkling needed?.
        /// </summary>
        public static string NeedToSprinkle {
            get {
                return ResourceManager.GetString("NeedToSprinkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprinkler number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprinkler open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of correction to be apply for automation.
        /// </summary>
        public static string PercentageCorrection {
            get {
                return ResourceManager.GetString("PercentageCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold for forecast data to be belived to be true.
        /// </summary>
        public static string PrecipitationPercentForecast {
            get {
                return ResourceManager.GetString("PrecipitationPercentForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold for actual precipitation when sprinkling is not needed.
        /// </summary>
        public static string PrecipitationThresholdActuals {
            get {
                return ResourceManager.GetString("PrecipitationThresholdActuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold for forecast precipitation when sprinkling is not needed.
        /// </summary>
        public static string PrecipitationThresholdForecast {
            get {
                return ResourceManager.GetString("PrecipitationThresholdForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        public static string ProgramTitle {
            get {
                return ResourceManager.GetString("ProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold for rain quantity.
        /// </summary>
        public static string RainMax {
            get {
                return ResourceManager.GetString("RainMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil humidity.
        /// </summary>
        public static string SoilHumidity {
            get {
                return ResourceManager.GetString("SoilHumidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprinkler.
        /// </summary>
        public static string Sprinkler {
            get {
                return ResourceManager.GetString("Sprinkler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprinkler number.
        /// </summary>
        public static string SprinklerNumber {
            get {
                return ResourceManager.GetString("SprinklerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        public static string SprinklerPrograms {
            get {
                return ResourceManager.GetString("SprinklerPrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprinklers.
        /// </summary>
        public static string Sprinklers {
            get {
                return ResourceManager.GetString("Sprinklers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprinkler.
        /// </summary>
        public static string SprinklerTitle {
            get {
                return ResourceManager.GetString("SprinklerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction in percent 100% = 100.
        /// </summary>
        public static string SprinklingMax {
            get {
                return ResourceManager.GetString("SprinklingMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start times.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum temperature.
        /// </summary>
        public static string TempMax {
            get {
                return ResourceManager.GetString("TempMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum temperature.
        /// </summary>
        public static string TempMin {
            get {
                return ResourceManager.GetString("TempMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time when automation process will check if sprinkling needed.
        /// </summary>
        public static string TimeToCheck {
            get {
                return ResourceManager.GetString("TimeToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone correction for sprinkler.
        /// </summary>
        public static string TimeZoneInfo {
            get {
                return ResourceManager.GetString("TimeZoneInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typical program.
        /// </summary>
        public static string TypicalProgram {
            get {
                return ResourceManager.GetString("TypicalProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit for forecasts.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User management.
        /// </summary>
        public static string UserTitle {
            get {
                return ResourceManager.GetString("UserTitle", resourceCulture);
            }
        }
    }
}
